---
name: "Platform Linter"

trigger: none

jobs:
  - job: lint
    displayName: "Linter job"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        path: self
        persistCredentials: true
      - script: docker pull ghcr.io/super-linter/super-linter:latest
        displayName: Pull GitHub Super-Linter image
      - script: >-
          docker run --rm --env-file "./.linter/super-linter.env" -v $PWD:/tmp/lint -w /tmp/lint ghcr.io/super-linter/super-linter:latest
        displayName: "Run GitHub Super-Linter"
      - task: PowerShell@2
        displayName: "Upload write/fix changes"
        inputs:
          targetType: "inline"
          script: |
            # Get-ChildItem env:
            $currentBranchName = $($env:SYSTEM_PULLREQUEST_SOURCEBRANCH).Split('/')[($($env:SYSTEM_PULLREQUEST_SOURCEBRANCH.Split('/')).count-1)]
            git config --global user.email 'devopsagent@dtx.nl'
            git config --global user.name 'DevOps Agent'
            git checkout $($currentBranchName)
            git add .
            git commit --allow-empty -m "Linter auto fix"
            git push origin $($currentBranchName)
        env:
          SYSTEM_ACCESSTOKEN: $(system.accesstoken)
