---
name: "_Platform: Linter"

on: # yamllint disable-line rule:truthy
  # push: null
  pull_request: null

permissions:
  contents: read

jobs:
  fix-lint-issues:
    permissions:
      # To write linting fixes
      contents: write
      # To write Super-linter status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Load super-linter configuration
        # Use grep inverse matching to exclude eventual comments in the .env file
        # because the GitHub Actions command to set environment variables doesn't
        # support comments.
        # Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
        run: grep -v '^#' .linter/super-linter.env >> "$GITHUB_ENV"
      - name: Super-Linter
        uses: super-linter/super-linter@2da136927bd4a73596db63044b504547c62cb854 # v9.0.0 x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set your fix mode variables to true
          # FIX_SHELL_SHFMT: true
          # FIX_YAML_PRETTIER: true
          # To reuse the same Super-linter configuration that you use in the
          # lint job without duplicating it, see
          # https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md#share-environment-variables-between-environments
      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: fix-lint-issues

    permissions:
      # contents permission to clone the repository
      contents: read
      packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
      issues: write
      pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Load super-linter configuration
        # Use grep inverse matching to exclude eventual comments in the .env file
        # because the GitHub Actions command to set environment variables doesn't
        # support comments.
        # Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
        run: grep -v '^#' .linter/super-linter.env >> "$GITHUB_ENV"
      - name: Super-linter
        uses: super-linter/super-linter@2da136927bd4a73596db63044b504547c62cb854 # v9.0.0 x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# ---
# name: "_Platform: Linter"

# on: [pull_request]
# permissions:
#   contents: read
#   packages: read
#   # To report GitHub Actions status checks
#   statuses: write

# concurrency: RunLinterOnlyOnce #can be any string, the second job will be queued after the first one is finished

# jobs:
#   build:
#     name: Lint
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           # super-linter needs the full git history to get the
#           # list of files that changed across commits
#           fetch-depth: 0
#       - name: Load super-linter configuration
#         # Use grep inverse matching to exclude eventual comments in the .env file
#         # because the GitHub Actions command to set environment variables doesn't
#         # support comments.
#         # Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
#         run: grep -v '^#' .linter/super-linter.env >> "$GITHUB_ENV"
#       - name: Super-linter
#         uses: super-linter/super-linter@latest # x-release-please-version
#         env:
#           # To report GitHub Actions status checks
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           DEFAULT_BRANCH: ${{ github.base_ref }}
